services:
  db:
    image: postgres:17
    container_name: mc-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: mcdb
    ports:
      - "5432:5432"
    volumes:
      - mc-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username $$POSTGRES_USER --dbname $$POSTGRES_DB" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  mc-db: {}