# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"\x12\n\x10TelemetryRequest\"\x97\x01\n\tTelemetry\x12\x0b\n\x03mac\x18\x01 \x01(\t\x12\x18\n\x10\x63urrent_position\x18\x02 \x01(\x02\x12\x17\n\x0ftarget_position\x18\x03 \x01(\x02\x12\x13\n\x0b\x62\x61ttery_soc\x18\x04 \x01(\x02\x12\x10\n\x08\x63harging\x18\x05 \x01(\x08\x12#\n\x04mode\x18\x06 \x01(\x0e\x32\x15.messages.TrackerMode* \n\x0bTrackerMode\x12\x08\n\x04\x41UTO\x10\x00\x12\x07\n\x03OFF\x10\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKERMODE']._serialized_start=202
  _globals['_TRACKERMODE']._serialized_end=234
  _globals['_TELEMETRYREQUEST']._serialized_start=28
  _globals['_TELEMETRYREQUEST']._serialized_end=46
  _globals['_TELEMETRY']._serialized_start=49
  _globals['_TELEMETRY']._serialized_end=200
# @@protoc_insertion_point(module_scope)
