services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222" # HTTP management port for information reporting.
      - "4222:4222" # For clients.
    command: "--http_port 8222"